graph TD
    
    classDef default fill:#f9f9f9,stroke:#333,stroke-width:2px;
    classDef usuario fill:#e1f5fe,stroke:#0288d1,stroke-width:2px;
    classDef nube fill:#fff3e0,stroke:#f57c00,stroke-width:2px;
    classDef api fill:#e8f5e9,stroke:#388e3c,stroke-width:2px;
    classDef endpoint fill:#fce4ec,stroke:#c2185b,stroke-width:2px;

   
    subgraph Cliente ["Acceso De usuarios"]
        User[Cliente Móvil Apliacion]
    end
    class User usuario;

    
    User -->|Request HTTP / HTTPS| Internet((Internet))

  
    subgraph Azure ["Nube de Azure"]
        subgraph Codespaces [" GitHub Codespaces"]
            
            
            subgraph FastAPI ["Framework: FastAPI"]
                
                direction TB
                
                EP1[" /evaluar-riesgo (POST)<br>Recibe: edad, ingresos, deudas<br>Estado: Protegido (datos válidos)"]
                EP2["/status (GET)<br>Devuelve: Estado de salud<br>Estado: Público (Sin autenticación)"]
                EP3["/datos-financieros/{id} (GET)<br>Devuelve: Historial por ID<br>Estado: VULNERABLE (Sin autenticación)"]
                
            end
        end
    end
    
    class Azure nube;
    class Codespaces nube;
    class FastAPI api;
    class EP1,EP2,EP3 endpoint;

   
    Internet -->|Encamina Peticiones| EP1
    Internet -->|Encamina Peticiones| EP2
    Internet -->|Encamina Peticiones| EP3

    
    EP1 -.->|Respuesta JSON<br>Aprobado / Rechazado / En Revisión| User
    EP2 -.->|Respuesta JSON| User
    EP3 -.->|Respuesta JSON| User

  
    style Codespaces stroke-dasharray: 5 5
